### ISSUE TITLE
->/assoc with constants doesn't work

### ISSUE THREAD

**Issue by 4ZM** [LonoCloud/synthread#6]
The documentation shows examples of using assoc with constants rather than functions, but this doesn't work.

Works fine:
`(-> {:fu 23} (->/assoc :fu inc)) => {:fu 24}`

Doesn't work:
`(-> {:fu 23} (->/assoc :fu 42))`

`ClassCastException java.lang.Long cannot be cast to clojure.lang.IFn  fu/eval1573 (NO_SOURCE_FILE:1)`

(btw, I would find it more natural to use ->/assoc to do the later, and a new ->/update to do the former in analogy with assoc-in/update-in)

**Comment by jclaggett** [comment]
In recent versions, assoc has been renamed to update. (closing)
